import type { Metadata } from "next";
import localFont from "next/font/local";
import { Provider } from "../app/Components/ui/Provider"
import "./globals.css";
import DiscountBanner from "../app/Components/discountBanner/DiscountBanner"

import Script from "next/script";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
        <head>
        <Script
          src="https://plausible.io/js/plausible.js"
          data-domain="chakra-ui.com"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Provider>
      <DiscountBanner
       announcementText="خصومات بنسبة 20% على الكورسات"
       startDate="2024-11-02T16:59:59"
       endDate="2024-11-09T23:59:59"
        />
       {children}
       </Provider>
      </body>
    </html>
  );
}


